version: "3.9"
services:
  back-end-app:
    build: back-end/
    ports:
      - "5000:5000"
  front-end-app:
    depends_on:
      - back-end-app
    build:
      context: front-end/
    ports:
      - "3000:3000"