route:
 group_by: [cluster]
 receiver: slack_general
 routes:
  - match:
      severity: slack
    receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - api_url: $API_URL
    channel: '#data-engineering-student-project'
