global:
  scrape_interval: 5s
  evaluation_interval: 10s
  
rule_files:
  - rules.yml
  
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
      
scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
  - job_name: "node"
    static_configs:
    - targets: ["localhost:9100"]
  - job_name: "data-engineering-project-2-back-end-app-1"
    static_configs:
    - targets: ["localhost:5000"]
            
remote_write:
  - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
    basic_auth:
      username: $GRAFANA_USERNAME
      password: $GRAFANA_PASSWORD