{
 "title": "Hardware",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) /            node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(\n  process_cpu_seconds_total{job=\"data-engineering-project-2-back-end-app-1\"}[30s]\n)"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"data-engineering-project-2-back-end-app-1\"}"
    }
   ]
  }
 ]
}