{
 "title": "Requests dashboard",
 "time": { "from": "2022-03-04T15:55:24.372Z", "to": "2022-03-04T17:16:16.180Z" },
 "panels": [
  {
   "title": "Request per seconds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Average requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Counter of requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "by_path_counter_total{path=\"/toxic\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request by status on toxic path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "requests_by_status_and_path_sum{path=\"/toxic\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Total Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Requests duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{status=\"200\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}